### ISSUE TITLE
[TODO] Create student versions of the notebooks

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#13]
This should be done pre-merge on PR #5.

**Comment by hugobowne** [comment]
I'll merge my PR https://github.com/ericmjl/bayesian-stats-modelling-tutorial/pull/8 before i create student NBs and then do so in another PR

**Comment by ericmjl** [comment]
Ok! (Sorry, I should have clarified - this was just a reminder for myself.)

**Comment by hugobowne** [comment]
Yah I thought so but I decided to jump on for the ride!

**Comment by hugobowne** [comment]
we're done here.
