### ISSUE TITLE
Style question

### ISSUE THREAD

**Issue by ronikobrosly** [ericmjl/bayesian-stats-modelling-tutorial#23]
Out of curiosity, what tool did you use to make the red distribution vector art? :)
As seen in problem 1, third notebook.

**Comment by ericmjl** [comment]
I used Illustrator! The original files are available in the `images/` directory, including the individual probability distributions used (both "prior" and "likelihood" versions are stored).

**Comment by ericmjl** [comment]
Images are MIT licensed, so feel free to use them however you like; though from an interpersonal standpoint, I'd have many warm fuzzy feelings if you referenced where they came from! :smile:

**Comment by ronikobrosly** [comment]
Great! Will do 👍

**Comment by ericmjl** [comment]
@ronikobrosly FYI I have created a separate repository where all of my individual distribution PDF files are located. Closing this issue; feel free to reopen if you need.
