### ISSUE TITLE
SciPy 2018 Post-Mortem

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#26]
@hugobowne I'm writing here some post-SciPy 2018 thoughts, gathered from my subjective view + participants' provided feedback in the feedback form.

# Overall Thoughts

## General reception to the tutorial was very positive

This was not just from the feedback provided in-person, but also from the feedback provided. Numerical ratings are available on [this report on TypeForm](https://ericma1.typeform.com/report/j88n8P/s8NhR0q27qrt5cyl).

## This has potential to be a 2-part tutorial

The amount of material covered in the first two hours might be better expounded on if we were to propose this as a two-part tutorial, each with a difference audience focus, with you leading the theory and hacker statistics section, and me leading the probabilistic programming session.

I came to this tentative conclusion only after reflecting on the tutorial's progress today. Here's my observations and thoughts so far:

### Probability basics: Definition, conditional, joint

1. As a refresher for probability, this section might have been heavy on material. (Refresher would target audience group 1: already knows stats, but just needs refresher).
1. As an in-depth introduction for probability, this section might have been light on material. (An in-depth introduction would target 
1. I'm having trouble imagining a group of people in the middle of these two general modes.

For those in the class that needed the in-depth introduction to probability, they really enjoyed your portion of the class. I think if we expanded your section to a full standalone tutorial, it might help learners get into the "distributional thinking" that is needed to work with a probabilistic programming language.

Now that I've had some space away from the material, I think that to introduce joint and conditional probability, starting with two-layer, binary tree-based probability example (e.g. cookie jar problem) might be more useful for audience group (probability novices), while Darwin's finches will be more useful for audience group 1 (probability intermediates/experienced). The cookie jar problem has a very intuitive "path-tracing" intuition to joint and conditional probability, and might help bridge "algebra to pictures" for a beginner (for which we had quite a number of in the SciPy crowd). On the other hand, it might not be complicated enough to be a meaningful refresher for audience group 1. Conditional and joint distribution with the Darwin's finches dataset might be a better fit there.

### Probabilistic Programming

(This is admittedly longer because I was more involved in it.)

I think the big lesson I learned from leading this section today was that a lecture + discussion format can still yield a meaningful tutorial experience for participants, but it isn't easily made inclusive of the whole class unless there is intentionally group discussion time scheduled in. Yet group discussion time takes time, and can eat into the opportunity to get practice in-class with the probabilistic programming exercises.

I think for the next iteration, I would redo the learning objectives of this section. Thinking more specifically about assumed knowledge, I would most ideally like to build on top of what you taught in Part 1, listed as follows:

- Able to simulate coin flips trials using `numpy`.
- Able to use resampling methods to estimate the confidence interval of a random variable parameter in a model.
- Proficient in Python syntax, including slice accessors into array-like objects, accessing values by key in a dictionary.
- Able to use a discrete example to describe what joint and conditional probability are.
- Able to define the mathematical relationship between conditional and joint probability, and derive Bayes' rule from their definition.
- Has performed the t-test.

Then, I would focus on the core, minimal set of Bayesian workflow steps, as described in an updated set of learning objectives. By the end of a workshop, a participant should be able to:

- Describe, justify, and use PyMC3 syntax to implement a data generative model for a data analysis problem, parameterized using probability distributions.
- Summarize posterior distributions as insights for a particular problem on hand.
- Critique the model using posterior predictive checks.

# Minutiae

## Socratic Discussion

The model building process is iterative, and should involve more of the kind of group discussion that occurred. 

To be more inclusive, I would probably schedule more "talk with your neighbours" followed by "share your discussion with the big group". This would allow the shier participants to engage in the class.

## Visuals

I have feedback that the model diagrams (red + white distributions) were helpful for thinking through the model building process. Had feedback that they should be introduced somewhat earlier in the class, though I'm not sure of the utility of this.

## Environment setup & checks

- [ ] Binder is always a good idea.
- [ ] Need more robust environment setup script. 
- [ ] Enforce more automated environment checks  with `checkenv.py`.

**Comment by ericmjl** [comment]
@hugobowne I'm writing here some post-SciPy 2018 thoughts, gathered from my subjective view + participants' provided feedback in the feedback form.

# Overall Thoughts

## General reception to the tutorial was very positive

This was not just from the feedback provided in-person, but also from the feedback provided. Numerical ratings are available on [this report on TypeForm](https://ericma1.typeform.com/report/j88n8P/s8NhR0q27qrt5cyl).

## This has potential to be a 2-part tutorial

The amount of material covered in the first two hours might be better expounded on if we were to propose this as a two-part tutorial, each with a difference audience focus, with you leading the theory and hacker statistics section, and me leading the probabilistic programming session.

I came to this tentative conclusion only after reflecting on the tutorial's progress today. Here's my observations and thoughts so far:

### Probability basics: Definition, conditional, joint

1. As a refresher for probability, this section might have been heavy on material. (Refresher would target audience group 1: already knows stats, but just needs refresher).
1. As an in-depth introduction for probability, this section might have been light on material. (An in-depth introduction would target 
1. I'm having trouble imagining a group of people in the middle of these two general modes.

For those in the class that needed the in-depth introduction to probability, they really enjoyed your portion of the class. I think if we expanded your section to a full standalone tutorial, it might help learners get into the "distributional thinking" that is needed to work with a probabilistic programming language.

Now that I've had some space away from the material, I think that to introduce joint and conditional probability, starting with two-layer, binary tree-based probability example (e.g. cookie jar problem) might be more useful for audience group (probability novices), while Darwin's finches will be more useful for audience group 1 (probability intermediates/experienced). The cookie jar problem has a very intuitive "path-tracing" intuition to joint and conditional probability, and might help bridge "algebra to pictures" for a beginner (for which we had quite a number of in the SciPy crowd). On the other hand, it might not be complicated enough to be a meaningful refresher for audience group 1. Conditional and joint distribution with the Darwin's finches dataset might be a better fit there.

### Probabilistic Programming

(This is admittedly longer because I was more involved in it.)

I think the big lesson I learned from leading this section today was that a lecture + discussion format can still yield a meaningful tutorial experience for participants, but it isn't easily made inclusive of the whole class unless there is intentionally group discussion time scheduled in. Yet group discussion time takes time, and can eat into the opportunity to get practice in-class with the probabilistic programming exercises.

I think for the next iteration, I would redo the learning objectives of this section. Thinking more specifically about assumed knowledge, I would most ideally like to build on top of what you taught in Part 1, listed as follows:

- Able to simulate coin flips trials using `numpy`.
- Able to use resampling methods to estimate the confidence interval of a random variable parameter in a model.
- Proficient in Python syntax, including slice accessors into array-like objects, accessing values by key in a dictionary.
- Able to use a discrete example to describe what joint and conditional probability are.
- Able to define the mathematical relationship between conditional and joint probability, and derive Bayes' rule from their definition.
- Has performed the t-test.

Then, I would focus on the core, minimal set of Bayesian workflow steps, as described in an updated set of learning objectives. By the end of a workshop, a participant should be able to:

- Describe, justify, and use PyMC3 syntax to implement a data generative model for a data analysis problem, parameterized using probability distributions.
- Summarize posterior distributions as insights for a particular problem on hand.
- Critique the model using posterior predictive checks.

# Minutiae

## Socratic Discussion

The model building process is iterative, and should involve more of the kind of group discussion that occurred. 

To be more inclusive, I would probably schedule more "talk with your neighbours" followed by "share your discussion with the big group". This would allow the shier participants to engage in the class.

## Visuals

I have feedback that the model diagrams (red + white distributions) were helpful for thinking through the model building process. Had feedback that they should be introduced somewhat earlier in the class, though I'm not sure of the utility of this.

## Environment setup & checks

- [ ] Binder is always a good idea.
- [ ] Need more robust environment setup script. 
- [ ] Enforce more automated environment checks  with `checkenv.py`.

**Comment by hugobowne** [comment]
@ericmjl can we close this and perhaps re-discuss the main points?
