### ISSUE TITLE
Windows: cannot run notebook

### ISSUE THREAD

**Issue by pllim** [ericmjl/bayesian-stats-modelling-tutorial#54]
I ran into a problem which has similar traceback as conda/conda#8171 . Despite that issue being marked as resolved and that I am using the latest release of conda 4.6.14, it still happened.

Tried some other things I found on the Internet like uninstalling and re-installing `pyzmq` and `jupyter` with either `conda` or `pip`. Didn't help.

In my case, the `activate` command gave some warnings about not able to find `vc/vcvarsall.bat`, which might or might not be related, as I could still use the environment.

At this point, I have wasted enough time on this, and thus my workaround is to re-create the tutorial enviroment without `jupyter`, `jupyterlab`, and `nodejs`, but add `ipython` to the YML, then run the examples inside a good ol' IPython session.

**Comment by ericmjl** [comment]
Oh my, I'm sorry you had to encounter this, @pllim. Yes, IPython should work. Should you decide that you'd like to use Jupyter again, I hope Binder serves as a feasible option for you.

I'm going to close this issue for now, but please feel free to re-open again if needed.

**Comment by pllim** [comment]
No problem. I opened this issue mainly so other Windows users can come here for group therapy. :smile:

**Comment by HanSeoulOh** [comment]
Also having this issue now all of a sudden after a windows reboot
