### ISSUE TITLE
modeling vs modelling

### ISSUE THREAD

**Issue by pllim** [ericmjl/bayesian-stats-modelling-tutorial#55]
American spelling is "modeling" with a single "l". :grimacing:

**Comment by ericmjl** [comment]
I've lived in ex-British colonies all my life 😁

**Comment by pllim** [comment]
Feel free to close if you want. I was just confused for half a day thinking you had a typo but then learned some interesting English grammar from the Internet. Just want to open this issue in case someone else is also confused like me.

**Comment by hugobowne** [comment]
I'm Australian

**Comment by machow** [comment]
TIL my spell-checker demands I stick to my American modelling roots

![image](https://user-images.githubusercontent.com/2574498/56684294-762bee80-669d-11e9-8e12-0f876408bbc3.png)

**Comment by hugobowne** [comment]
the plot thickens!
