### ISSUE TITLE
Setting up environment using binder session

### ISSUE THREAD

**Issue by psjms** [ericmjl/bayesian-stats-modelling-tutorial#59]
Hi, 
I am trying to set up environment using binder session for our class and I get error below.

"Failed to connect to event stream."

Has anyone else had this issue? Please advise.

Thank you.
PS.

**Comment by ericmjl** [comment]
@psjms it usually means that there was some timeout on Binder. I think a page refresh might do the trick?

**Comment by psjms** [comment]
Thank you, Eric. I am able to see the page.
PS.
