### ISSUE TITLE
JB's suggestions

### ISSUE THREAD

**Issue by justinbois** [ericmjl/bayesian-stats-modelling-tutorial#6]
Please view the following of constructive criticism!

## 1. Probability_a_simulated_introduction.ipynb
- I worry about your presentation of probability here. You are talking about frequency of events, not plausibility of a logical conjecture. Bayes Theorem is still valid, but why not present probability from a Bayesian perspective from the outset?
- I especially worry about this with the finch data set. You are sampling out of the empirical distribution function here, which could be really confusing for students when they start to think about likelihoods.
- I think maybe a better approach is to demonstrate sampling out of a distribution as a way to study it and understand it. For example, say we did not know that the number of coin flips resulting in heads out of *n* trials is Binomially distributed. We could get a handle on this distribution by simulating the coin flips, as you have done by drawing out of a Uniform distribution. You can get the same results as if you just plotted the PMF or CDF of a Binomial distribution (or its moments, whatever). This leads naturally into figuring out how we can understand a posterior by sampling out of it. And how can we sample out of a posterior? MCMC
- If you instead spent a little time on probability distributions and their stories, the students can get right to modeling and sampling (see below).
- I think this is about all you have to do and you can flow right into your next section.

## 2.Parameter_estimation_hypothesis_testing.ipynb
- I don't know if I'd use a Jeffreys prior. It's especially challenging to do a Jeffreys prior for the coin-flipping case. The Haldane or Uniform priors sort of make more intuitive sense, at least at first glance. Jeffreys priors come from Fisher information ideas, which can be tough to grasp. Rather, you might want to introduce ideas of informative or weakly informative priors.
- I actually wouldn't bother with mathematical expressions for the posteriors. Rather, just start busting out sampling. For example for the finch beaks, you can just specify the likelihood and prior and start sampling the posterior with PyMC3. For example, you can do the following, with all pertinent units in millimeters.
    beak depth | µ, σ ~ Norm(µ, σ)
    µ ~ Norm(10, 5)
    σ ~ LogNorm(0, 1)
So, with likelihood and prior specified, just start sampling.

## Summary
I think there are three main concepts you can get to in 4 hours. What a probability distribution is, the connection between the posterior distribution (what you want) and the likelihood and prior, and that you can sample out of the posterior (as specified by the likelihood and prior) using MCMC. The logical connection between the prior and posterior as the data updates belief is an important point. I think the hacker stats style sampling and the mathematical expressions/plots might get in the way of a more streamlined message.

**Comment by ericmjl** [comment]
@justinbois thank you for pinging in! There's very valuable pedagogical advice in your comments, things we've definitely looked over. We'll definitely be incorporating them in our tutorial!

**Comment by hugobowne** [comment]
@justinbois thanks for the feedback. I'm currently editing the material, will take all of this into consideration and will likely call you for a chat also! thanks once again.

One point worth noting is that the tutorial will be split into 2:

1. Two hours on intro. to probability/Bayes & parameter est./hypothesis testing using simulation techniques  (may end up being too much material);
2. Two hours on prob. programming/PyMC3

Does this knowledge alter any of you feedback?

**Comment by hugobowne** [comment]
@justinbois your feedback, Mike's feedback and 4th of July combined gave me wonderful inspiration today.

I've edited NB 1 accordingly. It's on this branch here: https://github.com/ericmjl/bayesian-stats-modelling-tutorial/blob/hugobowne-patch-1/notebooks/1.Probability_a_simulated_introduction.ipynb

We can discuss tomorrow

**Comment by hugobowne** [comment]
@justinbois I've been chewing on the case for busting out sampling for the Finch beak length example in Part 2 and I agree that it would be great to do it here.  

I have written a minimal example [here](https://github.com/ericmjl/bayesian-stats-modelling-tutorial/blob/hugobowne-patch-1/notebooks/pymc3_finch_example.ipynb). 

@ericmjl , how would you feel about me including this minimal example in the 2nd hour? It will allow us to avoid a lot of math at this point and make the pedagogy clearer and more precise. If I do introduce PyMC3 here, it may make sense for me to also use it for basic hypothesis testing in this section (see rest of [this notebook](https://github.com/ericmjl/bayesian-stats-modelling-tutorial/blob/hugobowne-patch-1/notebooks/2.Parameter_estimation_hypothesis_testing.ipynb)).

This is the code:

```
# Construct the model
with pm.Model() as finch_model:
    # Prior on mean, variance
    μ = pm.Normal('μ', mu=10, sd=5)
    σ = pm.Lognormal('σ', 0, 10)
    # Gaussian Likelihood
    y = pm.Normal('y', mu=μ, sd=σ, observed=df_12.blength)

# Sample from that shit!
with finch_model:
    samples = pm.fit(random_seed=42).sample(1000)
 
# Plot posterior
pm.plot_posterior(samples, varnames=['μ']);
```

and the result:

<img width="415" alt="screen shot 2018-07-04 at 8 10 37 pm" src="https://user-images.githubusercontent.com/4182382/42296640-5c0d46de-7fc6-11e8-91d8-662c6bab4efa.png">

**Comment by hugobowne** [comment]
also to discuss with JB

```
df_fortis = df_12.loc[df_12.species == 'fortis']
df_scandens = df_12.loc[df_12.species == 'scandens']

with pm.Model() as model:
    """
    The priors for each group.
    """
    μ_1 = pm.Normal('μ_1', mu=10, sd=5)
    σ_1 = pm.Lognormal('σ_1', 0, 10)
    μ_2 = pm.Normal('μ_2', mu=10, sd=5)
    σ_2 = pm.Lognormal('σ_2', 0, 10)
    ν = pm.Exponential('nu', lam=1/29) + 1
    # Gaussian Likelihoods
    y_1 = pm.Normal('y_1', mu=μ_1, sd=σ_1, observed=df_fortis.blength)
    y_2 = pm.Normal('y_2', mu=μ_2, sd=σ_2, observed=df_scandens.blength)
    # Calculate the effect size and its uncertainty.
    diff_means = pm.Deterministic('diff_means', μ_1 - μ_2)
# bust it out & sample
with model:
    samples = pm.fit(random_seed=42).sample(2000)
pm.plot_posterior(samples, varnames=['μ_1', 'μ_2', 'diff_means']);
```
aaaaaaand:

<img width="784" alt="screen shot 2018-07-04 at 8 38 43 pm" src="https://user-images.githubusercontent.com/4182382/42297055-4808bb38-7fca-11e8-9ef3-ba3689de3ef4.png">

**Comment by ericmjl** [comment]
@hugobowne 

> @ericmjl , how would you feel about me including this minimal example in the 2nd hour? It will allow us to avoid a lot of math at this point and make the pedagogy clearer and more precise. If I do introduce PyMC3 here, it may make sense for me to also use it for basic hypothesis testing in this section (see rest of this notebook).

I think this makes a ton of sense! I was fretting over the fact that the basic estimation stuff hadn't been covered in PyMC3 prior to working out case/control comparison.

**Comment by hugobowne** [comment]
closing as dealing with all of this here: https://github.com/ericmjl/bayesian-stats-modelling-tutorial/pull/8
