### ISSUE TITLE
NB1: discrete probability distribution histograms should be bar charts.

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#60]
As per title.

**Comment by hugobowne** [comment]
yeh this is tough in matplotlib w/out introducing a bunch more code. ill try to solve this by setting number of bins

**Comment by hugobowne** [comment]
resolved in https://github.com/ericmjl/bayesian-stats-modelling-tutorial/commit/9976277f8fa5d695138697b6e840a66b2267cfdc
