### ISSUE TITLE
NB1: Perhaps a figure at the end of joint/conditional distribution?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#61]
It's this figure:

![](https://ericmjl.github.io/blog/2018/8/7/joint-conditional-and-marginal-probability-distributions/joint-conditional-marginal.png)

Minus the "marginal distribution" portion.

**Comment by hugobowne** [comment]
great idea!

**Comment by hugobowne** [comment]
Added in https://github.com/ericmjl/bayesian-stats-modelling-tutorial/commit/9976277f8fa5d695138697b6e840a66b2267cfdc
