### ISSUE TITLE
Class feedback: Use scatter plot?

### ISSUE THREAD

**Issue by pllim** [ericmjl/bayesian-stats-modelling-tutorial#64]
In the ECDF examples, maybe

```python
plt.plot(x, y, marker='.', linestyle='none');
```

can be replaced with

```python
plt.scatter(x, y)
```

?

**Comment by ericmjl** [comment]
Absolutely :smile:.

**Comment by hugobowne** [comment]
Yes. Sometimes people like to plot ECDFs with the steps & it's easier to customize 

```
plt.plot(x, y, marker='.', linestyle='none');
```

in this case

**Comment by pllim** [comment]
Ah, okay. Feel free to close if irrelevant. Thanks for the clarification.

**Comment by hugobowne** [comment]
Not irrelevant at all!
