### ISSUE TITLE
Distributions as 1st class citizens?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#67]
Could there be a restructuring of NB2's pre-PPL content, such that the "distributions as 1st-class citizens" could be emphasized? I have a hunch that this might help with learning.

I suspect that maybe using scipy.stats could help? It helps reinforce the idea that:

1. PDFs are nothing more than just math functions.
2. Calculation of likelihood is all "just" functions.
3. Math can be abstracted.

**Comment by hugobowne** [comment]
lets discuss this. wrt your point 1, a major reason for doing this by simulation is to take an alternative path to the math, with the aim of lowering the barrier to entry.

also remember the carpentries' & @gvwilson's thoughts on using the term 'just' in pedagogy! I recall you'd be fined a dollar for each use of it! :D 

i definitely believe we could emphasize "distributions as 1st-class citizens" as much as we want. it's such an important take-away. i'm not sure scipy.stats is the answer. 

i think simulation and probabilistic storytelling is viable path here.

**Comment by hugobowne** [comment]
@ericmjl what do you mean by "Math can be abstracted"?

**Comment by ericmjl** [comment]
This one was also post-PyCon, so I think it’s old.
