### ISSUE TITLE
Modularity in content

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#72]
We need to modularize nb1 & 2. 

Also need to restructure 3 onwards.

NB3 onwards:

- Group comparison
- Arbitrary curve regression

**Comment by hugobowne** [comment]
i'll own this for NBs 1&2. i plan to split them into 4:

1. probability distributions & their stories
2. joint/conditional probability & bayes rule
3. Bayesian inference: intro. to priors, likelihoods & posteriors
4. Bayesian workflow & intro. to PPL

@ericmjl that's what we discussed, yah?

**Comment by ericmjl** [comment]
YAEAHHHHHHHH!!

**Comment by hugobowne** [comment]
dude we're about to take this to the NEXT LEVEL.

**Comment by hugobowne** [comment]
@ericmjl I'll have this done by July 1st. Does that work?

**Comment by ericmjl** [comment]
Works for me as well; I also need to carve out some time to make my changes.

**Comment by hugobowne** [comment]
closing as this was for scipy, july, 2019. feel free to reopen.
