### ISSUE TITLE
Update title/abstract; draft email to SciPy 2019 attendees

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#75]
**Title:** Bayesian Data Science: Probabilistic Programming

**Abstract:** This tutorial will introduce you to the wonderful world of Bayesian data science through the lens of probabilistic programming. In the first hour of the tutorial, we will begin reintroduce the key concept of probability distributions via hacker statistics, hands-on simulation and telling stories of the data-generation processes. We will also cover the basics joint and conditional probability, and Bayes' rule and Bayesian inference. In the latter 2/3 of the tutorial, we will use a series of models to build your familiarity with PyMC3, showcasing how to perform the foundational inference tasks of group comparison and arbitrary curve regression. By the end of this tutorial, you will be equipped with a solid grounding in Bayesian inference, able to write arbitrary models, and have experienced basic model checking workflow.

**Notes to registered attendees:**

Dear all,

We (Hugo and myself) have reviewed the tutorial schedule, and after discussing with the SciPy tutorial committee and the instructors before and after us in the schedule, we have proposed to deliver a tutorial that focuses on probabilistic programming instead of simulation. The tutorial committee has given us the green light for this change, and we thought it would be only right to inform you of the change and guide you on how to best prepare for the updated tutorial.

The motivation is as follows: Our simulation-based tutorial covers the basic concepts of Bayesian inference through the lens of simulation, which overlaps with Allen Downey's content. In addition, the tutorial after us covers Bayesian model checking using ArviZ, for which it would be very helpful to have had a longer session on probabilistic programming first. Taken together, we envision this as a "Bayes Track"-ish series at SciPy, where our tutorials can exist independently (because we do have enough recap on our own), but complement each other very well nonetheless; the sections that overlap hopefully give sufficient repetition for learning without being overly repetitive. 

As such, this tutorial requires basic knowledge in Bayesian inference and probability. You can gain this knowledge for SciPy 2019 in one of two ways. You may either 
- register for Allen Downey's ["Bayesian Statistics Made Simple" tutorial](https://www.scipy2019.scipy.org/tutorial/Bayesian-Statistics-Made-Simple), or 
- watch our [PyCon 2019 tutorial "Bayesian Data Science: Simulation"](https://www.youtube.com/watch?v=0pZc5u3e884). 

Attendance in Allen's tutorial is not a mandatory prerequisite, but highly encouraged; that said, we will cover enough material to ground our material in the recap. Additionally, if you would like to have a stronger grounding on probabilistic programming prior to attending the ArviZ tutorial led by Ravin Kumar and Colin Carroll, our tutorial would be a helpful starting point, though they will also be covering the basics of probabilistic programming for their tutorial. With that all said, we think attending all three would be extremely beneficial for your knowledge development in Bayesian inference, and there _might probably_ be a gift for you from the instructors if you've braved through all three this year!

If you have questions regarding the tutorial, please feel free to reach out to us. Our preferred method of communication is on the [GitHub issue tracker](https://github.com/ericmjl/bayesian-stats-modelling-tutorial/issues), where questions we have addressed before can be publicly viewable by others and searchable.

Cheers,
Eric & Hugo

**Comment by canyon289** [comment]
LGTM

**Comment by hugobowne** [comment]
- I would **challenge** SciPy attendees to go to ALL 3 Bayesian tutorials.

In abstract, how about edit 

> In this tutorial, we will begin by recapping probability distributions and their "generative stories"

to

> In this tutorial, we will begin by re-introducing the key concept of probability distributions via hacker statistics, hands-on simulation and telling stories of the data-generation processes.

?

**Comment by ericmjl** [comment]
> I would challenge SciPy attendees to go to ALL 3 Bayesian tutorials.

Belly of fire there, Hugo! 😆

I'll _encourage_ them to go for it. We're from British colonies, we're supposed to be un-American 
and nice (whoops!!!!!, I jest!!!!).

**Comment by hugobowne** [comment]
We could have a give-away for people who attend all 3 Bayesian tutorials, in which the winner **probably** gets a prize.

**Comment by canyon289** [comment]
I support at @hugobowne's challenge and happy to with a prize and bestow honor upon such a committed attendee!

**Comment by AllenDowney** [comment]
LGTM!

**Comment by hugobowne** [comment]
We look good to go here.
