### ISSUE TITLE
Notes for EM teaching HBA's material SciPy 2019

### ISSUE THREAD

**Issue by hugobowne** [ericmjl/bayesian-stats-modelling-tutorial#78]
There's a chance that I may not make SciPy  due to family health reasons and @ericmjl will teach the material I would have.

This issue contains notes for Eric to do so.

I have split NBs 1 & 2 into 2 NBs each:

-  1a on probability distributions and their stories
- 1b on joint/cond. probs & Bayes' Rule
- 2a on "from Bayes' rule to Bayesian inference"
- 2b on PP and Bayesian workflow

I recall that we were going to  spend 90 minutes on this material  and that we would cover NBs 1a &  2b in detail, while covering 1b/2a more cursorily.

TBD w/ @ericmjl & we'll drop more notes in here

**Comment by hugobowne** [comment]
we discussed & eric taught successfully

**Comment by ericmjl** [comment]
> “taught successfully”

_Maybe_.  :smile:

I’ll post a post-mortem of SciPy 2019’s feedback on a separate post.
