### ISSUE TITLE
ECDF function in util.py not returning right values

### ISSUE THREAD

**Issue by pydatawrangler** [ericmjl/bayesian-stats-modelling-tutorial#81]
Eric:

Very much enjoy your tutorials on bayesian inference and PYMC.

There was something I noticed in the repo files that confused me a litte.  The ecdf function you defined in the notebook (01a-instructor-probability-simulation.ipynb) differs from the ECDF function in the utils.py script.  The one in the notebook is below, and gives me the results I expect:

### FROM NOTEBOOK

```python
def ecdf(data):
    """Compute ECDF for a one-dimensional array of measurements."""
    # Number of data points
    n = len(data)

    # x-data for the ECDF
    x = np.sort(data)

    # y-data for the ECDF
    y = np.arange(1, n+1) / n

    return x, y
```

However, the ECDF function in the utils.py script (below) does not give me the results I expect:

### FROM `utils.py` SCRIPT

```python
def ECDF(data):
    x = np.sort(data)
    y = np.cumsum(x) / np.sum(x)
    
    return x, y
```

Is there an error in the utils.py script?

Thanks,
Tom

**Comment by ericmjl** [comment]
@pydatawrangler thanks for pinging in, Tom!

Definitely there's an error here. The one in the notebook is definitely the correct one. Thank you for catching this bug!

Btw, an idea came to mind: would you be open to submitting a PR to fix this? I could fix this really quickly, but I'm usually more inclined to give others an opportunity to make a contribution to the learning material, especially if they're a first-time contributor to open source. It's also my little way of helping out with community building.

I'll let you make the call here - I'm good both ways, so please let me know!

**Comment by pydatawrangler** [comment]
Will do!

I need some practice in PRs anyway.

Thanks,
Tom
