### ISSUE TITLE
Modified finches beak dataset

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/bayesian-stats-modelling-tutorial#9]
@hugobowne, if you look [this commit](https://github.com/ericmjl/bayesian-stats-modelling-tutorial/pull/5/commits/f9bb4b21743a2ea2a9f414b1f0d26bd880a0bb5e), you will find that in my branch, I have added one row of data to the finches 2012 dataset.

This simulates the discovery of a new species of finch, for which the only thing we know is that it is genetically related. **There is a teaching moment baked into this**: if we did not do hierarchical modelling, where we assumed that the new species of finch was genetically related to the known finches, then on the basis of a single observation, we would get posterior estimates for beak length that were unreasonable. 

More details will be found in the notebooks that I'm finishing up right now. Working through this particular example just reinforced for me the elegance of using hierarchical modelling where relatedness is a reasonable assumption.

Anyways, that was just a longwinded way of informing you of the minor addition made to the dataset, and I just didn't want to give you unnecessary surprises there!

**Comment by hugobowne** [comment]
Thanks, @ericmjl, that makes sense. Pretty excited to check out this teaching moment for hierarchical modelling. I'll close this issue and re-open, if necessary.
